#!/usr/bin/env php
<?php

if (isset($argv[1]) && $argv[1] === '--build-all') {
    unset($argv[1]);

    $argv = array_values($argv);
    $argc = count($argv);

    $_SERVER['argv'] = $argv;
    $_SERVER['argc'] = count($argv);

    require_once __DIR__.'/tests/BuildAllBootstrap.php';
}

require_once 'vendor/bin/phpunit';
